version: "3.8"

services:
  dan-gateway:
    container_name: dan-gateway
    build:
      context: ../dan-gateway/
      dockerfile: ./Dockerfile
    ports:
      - 3080:8080
    environment:
      - spring.profiles.active=default
    networks:
      - dan-db-network

  dan-appui:
    container_name: dan-appui
    build:
      context: ../dan-ui/
      dockerfile: ./Dockerfile
    ports:
      - 9500:3000
    networks:
      - dan-db-network

  dan-haproxy:
    container_name: dan-haproxy
    build:
      context: ../dan-haproxy/
      dockerfile: ./Dockerfile
    image: haproxy:latest
    ports:
      - "80:80"
      - "3443:443"
    networks:
      - dan-db-network
    depends_on:
      - dan-gateway

networks:
  dan-db-network:
    driver: bridge
